# Generated by Django 3.1.5 on 2021-01-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210117_1540'),
        ('products', '0002_auto_20210117_1246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductModel',
        ),
    ]
